### ISSUE TITLE
Good job,Thanks, Is open source?

### ISSUE THREAD

**Issue by chaomengnan** [Exzap/Cemu#1]

**Comment by jackwilsdon** [comment]
+1

**Comment by semihmasat** [comment]
I know this is experimental but if you open source it, we might help you.

And learn a lot with your code.

**Comment by DasBiest** [comment]
Please add the sourcecode into the repo, so we can help and learn :+1:

**Comment by rahulroy9202** [comment]
yes. please open source it.

**Comment by DistantThunder** [comment]
For a project of this scale, I cannot advocate enough for you to open source it. You'll get plenty of help from very experienced people (won't be surprised if big shots from PPSSPP, Dolphin and PCSX2 show up) and you'll allow many people to learn from your code.

**Comment by filfat** [comment]
+1

**Comment by sasukedotca** [comment]
Yeap, you may benefit from the already started project exjam/wiiu-emu..

**Comment by dadziokPL** [comment]
Yes please, make this open source. We can look through the source code, learn, help with the emu, and check if there are no viruses or something ;)

**Comment by Margen67** [comment]
+1

**Comment by pjc1990** [comment]
you should charge for the emulator like connectix virtual game station I'd pay good money for that ;)

**Comment by gappleto97** [comment]
+1

**Comment by laetemn** [comment]
The source code is available here: https://github.com/Exzap/Cemu/releases

**Comment by gappleto97** [comment]
Except this does not allow anyone to really participate. If you use it with
git, then people can assist far more easily.

**Comment by pauldacheez** [comment]
No actual source in there anyway, it's just a readme.

**Comment by Margen67** [comment]
Exzap responded to me http://i.imgur.com/lNRJKeX.png

**Comment by tux1c** [comment]
If you are going to release it's source, please consider using a free license #3 
the title says it all.
A free license will ensure the user's freedom, and that the project doesn't eventually die out of neglect (some non-free licenses may cause issues with other people taking the source and changing it and/or distributing it), as well as increase the support from the community (code-wise and support wise)

**Comment by waddlesplash** [comment]
@Exzap: You realize that statically linking wxWidgets (a LGPL project) without releasing the source code breaks the LGPL, as you must be allowed to re-link LGPL software? So this project as-is violates the LGPL.

**Comment by waddlesplash** [comment]
EDIT: disreguard.

**Comment by mikelpr** [comment]
>hosted on github
>closed source

wat

**Comment by roflcopter777** [comment]
@mikelpr  IRK?

**Comment by abermea** [comment]
The project isn't actually hosted on github, though. It's only a README.md file

**Comment by ScoreUnder** [comment]
@abermea It is being hosted on github: https://github.com/Exzap/Cemu/releases

**Comment by chaomengnan** [comment]
closed it.We are very interested about the source,hope the author release it,but this is author's right,we have no right to interfere.
