### ISSUE TITLE
If you are going to release it's source, please consider using a free license

### ISSUE THREAD

**Issue by tux1c** [Exzap/Cemu#3]
the title says it all.
A free license will ensure the user's freedom, and that the project doesn't eventually die out of neglect (some non-free licenses may cause issues with other people taking the source and changing it and/or distributing it), as well as increase the support from the community (code-wise and support wise)

**Comment by faissaloo** [comment]
I agree, please use GPL v2, because it will also mean that if people patch the project they have to give their patches back so everyone benefits

**Comment by tux1c** [comment]
@faissaloo why not v3? :)

**Comment by Margen67** [comment]
+1

**Comment by faissaloo** [comment]
@tux1c I've heard bad things about v3

**Comment by tux1c** [comment]
@faissaloo most are FUD, though.
The v3 basically only covers some v2 issues and also bans using DRM on free software (for example, you buy my router which runs free software, and you are free to redistribute it and all the freedoms given by the GPL, but you simply can't install your modified version back on the router. v3 bans this scenario)

**Comment by laetemn** [comment]
The source code is available here: https://github.com/Exzap/Cemu/releases

**Comment by sasukedotca** [comment]
It's not available..it's a zip of what is in the git, readme.md

**Comment by Margen67** [comment]
Exzap responded to me http://i.imgur.com/lNRJKeX.png

**Comment by tux1c** [comment]
@Margen67 awwww that's a shame, another emulator I'd have to miss out :( I wonder what is up with all of the proprietary emulators lately.

I guess I'll keep this open in case they ever do release the src code.

**Comment by Margen67** [comment]
Exzap responded again http://gbatemp.net/threads/release-cemu-wii-u-emulator.399524/page-22#post-5728863

**Comment by tux1c** [comment]
actually, closing it in order to make as little pollution as possible. a bunch of issues that talk about the same is annoying. let's keep it all in #1.

**Comment by VelocityRa** [comment]
Exzap explains in detail why he doesn't want open-source development [here](https://www.reddit.com/r/cemu/comments/3ou88k/rcemu_is_now_open/cw0x5q8).
It's not gonna happen guys, may as well close all issues that beg for it.
